name: Dart

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get
        working-directory: ./snapnfix

      - name: Analyze project source
        run: dart analyze
        working-directory: ./snapnfix

      - name: Run tests
        run: dart test
        working-directory: ./snapnfix
